import pandas as pd
df = pd.read_csv('heart.csv')
print(df.head())
#print(df.tail())
print(df.info())
print(df.describe())
df = pd.read_csv('dz.csv')
print(df)
#print(df.info())
group = df.groupby('City')['Salary'].mean()
print(group)
